method : DeepJSCC
sub_method: IB
dataset: mnist
task: classification
embd_dim: 24
t_num: 1
bs: 64
beta: 0.001
lr: 0.0001
cuda: 0
encoder_model: ToyNet
decoder_model: LinearModel
epochs: 100
channel_setting: [[1,0]]
PSNR: False
seed: 2025


# python main.py --config_file_path "./train_yaml/MNIST_IBJSCC.yaml"