method : DT_VQVAE
dataset: mnist
task: classification
embd_dim: 64
t_num: 1
bs: 64
beta: 0.001
lr: 0.0001
cuda: 0
encoder_model: ToyNet
decoder_model: Classifier
epochs: 100
seed: 2025

# python main.py --config_file_path "./train_yaml/MNIST_DT_VQVAE.yaml"